---
- hosts: management
  become: true
  tasks:
  - name: Run script to install crontab
    script: /tmp/monitoring/create_crontab.sh
  - name: Install mailutils postfix for sending emails 
    apt: pkg={{ item }} update_cache=yes
    with_items:
      - mailutils
      - postfix
    sudo: yes
  - name: Listen only on local interface
    lineinfile: dest=/etc/postfix/main.cf regexp='^inet_interfaces' line='inet_interfaces = 127.0.0.1'