---
- hosts: loadbalancer
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: Ansible delete file example
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
    - name: Setup nginx conf
      template:
        src=/shared/ansible/nginx.conf
        dest=/etc/nginx.conf
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: /shared/ansible/default-lb
        dest: /etc/nginx/sites-enabled/
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes