---
- hosts: loadbalancer
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: Ansible delete file example
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
    - name: Setup nginx conf
      template:
        src=/shared/ansible/configs/nginx/default-lb
        dest=/etc/nginx/nginx.conf
      notify: restart nginx
  handlers:
      - name: start nginx
        become: yes
        service:
          name: nginx
          state: started
      - name: restart nginx  
        become: yes
        service:
          name: nginx
          state: restarted
        
        