---
- hosts: all
  become: true
  tasks:
    - name: Add user to sudoers file
      lineinfile:
        path: /etc/sudoers
        regexp: '^vagrant'
        line: 'vagrant ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'