---
- name: 1. install Apache
  apt: name=apache2 state=present
  become: true

- name: 2. install list of PHP modules for Apache
  apt: name={{item}} state=present
  with_items:
    - libapache2-mod-php
    - libapache2-mod-security2
  become: true

- name: 3. start Apache
  service: name=apache2 state=started enabled=yes
  become: true

- name: 4. remove default apache index 
  file: 
    path: /var/www/html/index.html
    state: absent
  become: true

- name: 5. install Hello World PHP script
  copy: src=../files/index.php dest=/var/www/html/index.php mode=0664
  become: true
